name: Build Snapshot Scrapper


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push the Docker Image
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/edgeandnode/snapshot-scrapper
          tag-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push the container image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{steps.docker_meta.outputs.tags}}
          labels: ${{steps.docker_meta.outputs.labels}}
          build-args: NPM_TOKEN=${{secrets.graphprotocol_npm_token}}
